#pragma once

#define GRID_HEIGHT 10
#define GRID_WIDTH 10
#define SCALE_FACTOR 4
#define TILE_SQUARE_SIZE 16
#define TILE_SCALED_SIZE (TILE_SQUARE_SIZE * SCALE_FACTOR) // 64

#define GAME_WINDOW_WIDTH (TILE_SCALED_SIZE * GRID_WIDTH) // 640
#define GAME_WINDOW_HEIGHT (TILE_SCALED_SIZE * GRID_HEIGHT) // 640